name: hawaii
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


#---------------------------------------------PACKAGES-----------------------------------------------#
dependencies:
  flutter:
    sdk: flutter


  # Utilities Packages:
  http: ^0.13.3
  gap: ^3.0.1
  carousel_slider: ^4.0.0
  liquid_swipe: ^3.1.0
  cached_network_image: ^3.0.0



  # Icon Packages:
  cupertino_icons: ^1.0.2
  fluentui_icons: ^1.0.0
  lottie: ^2.3.1

  # Fonts:
  line_awesome_flutter: ^2.0.0
  font_awesome_flutter: ^10.4.0
  intl: ^0.18.1
  google_fonts: ^4.0.4

  #State Management
  get: ^4.3.8

  #Others
  flutter_otp_text_field: ^1.1.1
  flutter_native_splash: ^2.2.19

  #Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0



#---------------------------------------------PACKAGES END-----------------------------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter





  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  #---------------------------------------------Local Assets-----------------------------------------------#
  assets:
    - assets/
    - assets/images/
    - assets/images/logos/
    - assets/images/banners/
    - assets/images/destination/

