// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC43URMeCiQz4Etc8tmZc_oIjjMPHC4u48',
    appId: '1:569404053614:web:c33010b47777eacc446e7f',
    messagingSenderId: '569404053614',
    projectId: 'hawaii-99a32',
    authDomain: 'hawaii-99a32.firebaseapp.com',
    storageBucket: 'hawaii-99a32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApkKbTwZ0SpC8Se-MEH_0GU6bFLkkdUW8',
    appId: '1:569404053614:android:43be8524406fae9d446e7f',
    messagingSenderId: '569404053614',
    projectId: 'hawaii-99a32',
    storageBucket: 'hawaii-99a32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXPJlnuvqDGzj8l-C2WASTe7kDhqoBosA',
    appId: '1:569404053614:ios:213973416c1e600b446e7f',
    messagingSenderId: '569404053614',
    projectId: 'hawaii-99a32',
    storageBucket: 'hawaii-99a32.appspot.com',
    iosBundleId: 'zucode.io.hawaii',
  );
}
